#!/usr/bin/env python3
"""Write packages/yst_credentials/_embedded.py from secrets/.master.key"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KEY_FILE = ROOT / "secrets" / ".master.key"
OUT = ROOT / "packages" / "yst_credentials" / "_embedded.py"


def main() -> None:
    if not KEY_FILE.exists():
        raise SystemExit(f"Run encrypt_secrets.py first to create {KEY_FILE}")
    b64 = KEY_FILE.read_text().strip()
    OUT.write_text(
        '# Generated by scripts/embed_key.py — personal build only.\n'
        f'EMBEDDED_KEY_B64 = "{b64}"\n',
        encoding="utf-8",
    )
    print(f"Updated {OUT}")


if __name__ == "__main__":
    main()
